apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp-servicemonitor
  labels:
    release: prometheus   
spec:
  selector:
    matchLabels:
      app: myapp           
  endpoints:
    - port: http           
      path: /metrics
      interval: 15s
      scheme: http
